# Handling multiple sequences

In [39]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = ["I’ve been waiting for a HuggingFace course my whole life.", "I hate this so much!"]

tokenized_inputs = tokenizer(sequence, padding=True, truncation=True, return_tensors="pt")
# print(tokenized_inputs["input_ids"])
# ids = tokenizer.convert_tokens_to_ids(tokenized_inputs)
# print(ids)
# input_ids = torch.tensor(tokenized_inputs["input_ids"])
# This line will fail.
print(tokenized_inputs)
output = model(**tokenized_inputs)
# ids = tokenizer.convert_tokens_to_ids(tokenized_inputs)
# print(ids)

# input_ids = torch.tensor([ids])
# print("Input IDs:", input_ids)

# output = model(input_ids)
print("Logits:", output.logits)


{'input_ids': tensor([[  101,  1045,  1521,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}
Logits: tensor([[-1.5979,  1.6390],
        [ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>)


In [36]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence =[ "I hate this so much!"]

tokenized_inputs = tokenizer(sequence)
# print(tokenized_inputs["input_ids"])
# ids = tokenizer.convert_tokens_to_ids(tokenized_inputs)
# print(ids)
input_ids = torch.tensor(tokenized_inputs["input_ids"])
# This line will fail.

output = model(input_ids)
# ids = tokenizer.convert_tokens_to_ids(tokenized_inputs)
# print(ids)

# input_ids = torch.tensor([ids])
# print("Input IDs:", input_ids)

# output = model(input_ids)
print("Logits:", output.logits)


Logits: tensor([[ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>)


In [14]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence1_ids = [[200, 200, 200]]
sequence2_ids = [[200, 200]]
batched_ids = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id],
]

print(model(torch.tensor(sequence1_ids)).logits)
print(model(torch.tensor(sequence2_ids)).logits)
print(model(torch.tensor(batched_ids)).logits)

tensor([[ 1.5694, -1.3895]], grad_fn=<AddmmBackward0>)
tensor([[ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)
tensor([[ 1.5694, -1.3895],
        [ 1.3374, -1.2163]], grad_fn=<AddmmBackward0>)


In [15]:
batched_ids = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id],
]

attention_mask = [
    [1, 1, 1],
    [1, 1, 0],
]

outputs = model(torch.tensor(batched_ids), attention_mask=torch.tensor(attention_mask))
print(outputs.logits)

tensor([[ 1.5694, -1.3895],
        [ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)


In [66]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

ids1 = tokenizer.encode("I've been waiting for a HuggingFace course my whole life.")

ids2 = tokenizer.encode("I hate this so much!")
# Pad the sequences to the same length
max_length = max(len(ids1), len(ids2))
ids1_padded = ids1 + [tokenizer.pad_token_id] * (max_length - len(ids1))
ids2_padded = ids2 + [tokenizer.pad_token_id] * (max_length - len(ids2))

input_ids = torch.tensor([ids1_padded, ids2_padded])
attention_mask = torch.tensor([[1] * len(ids1_padded), [1] * len(ids2_padded)])
print("Input IDs:", input_ids)

output = model(input_ids, attention_mask=attention_mask)
print("Logits:", output.logits)

Input IDs: tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]])
Logits: tensor([[-1.5607,  1.6123],
        [ 3.4603, -2.9194]], grad_fn=<AddmmBackward0>)


In [65]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence =  "I hate this so much!"

tokens = tokenizer(sequence,return_tensors="pt")

output = model(**tokens)
print("Logits:", output.logits)

Logits: tensor([[ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>)
